language: haskell

ghc:
  - "8.2.2"

before_install:
  - sudo apt purge cabal*
  - sudo apt install cabal-install-2.2
  - cabal-2.2 --version || cabal --version || cabal-install-2.2 --version || /opt/cabal/bin/cabal --version