language: haskell

ghc:
  - "8.2.2"

before_install:
  - sudo apt purge cabal*
  - sudo apt install cabal-install-2.2
  - /opt/cabal/bin/cabal --version
  - alias myCabal='/opt/cabal/bin/cabal'

install:
  - myCabal install --only-dependencies --enable-tests

script:
  - myCabal configure --enable-tests && myCabal build && myCabal test